# Generated by Django 5.0.7 on 2024-07-24 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='документ')),
                ('status', models.CharField(choices=[('в обработке', 'В обработке'), ('принят', 'Принят'), ('отклонен', 'Отклонен')], default='в обработке', max_length=20, verbose_name='Статус документа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время доставки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
