# Generated by Django 5.0.7 on 2024-07-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rejection_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к отклонению'),
        ),
    ]
